plugins {
    id 'com.android.application'
}

android {
    namespace 'com.supermarket.calculator'
    compileSdk 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        applicationId "com.supermarket.calculator"
        minSdk 21
        targetSdk 34
        versionCode 20
        versionName "20"
    }

    signingConfigs {
        release {
            storeFile     file("keystore.jks")
            storePassword "android123"
            keyAlias      "app"
            keyPassword   "android123"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            if (variant.buildType.name == 'release') {
                outputFileName = "超市计算器V${variant.versionName}.apk"
            }
        }
    }
}

dependencies {
}
